### ISSUE TITLE
Form freeze when rise method

### ISSUE THREAD

**Issue by Radzhab** [BAPostma/TelegramBot.Net#1]
```
 Bot bot = new Bot("123456:AAHH3aB2J9WpEuaFajn7H2ugvlBW_fu7-NE");
  var data = bot.GetMe();
  MessageBox.Show(data.ToString());
```

why it freeze form?

**Comment by BAPostma** [comment]
The GetMe() method is a synchronous call that is most likely blocking your UI thread, freezing it until a response has been received. Try using the GetMeAsync() method and read up on the C# async/await keywords, they'll help you out.

Cheers, Barry
